### ISSUE TITLE
pndev shell does not exit after killing ember server with `ctrl-c`

### ISSUE THREAD

**Issue by christophermlne** [PrecisionNutrition/pndev#10]
__Steps to reproduce__
- from within the `es-student` (or `es-certification`) folder, run `pndev start`
- try to quick the ember server after it has started with `ctrl-c`

__Actual__
- shell hangs on message 'Cleaning up...'

__Expected__
- shell should exit cleanly

**Comment by ghedamat** [comment]
so I did a bunch of research 

it is not hanging up and it does exit cleanly

but because of how processes work in UNIX
when you send CTRL+C (which sends the SIGTERM signal) `pndev` is killed

that in turns kills `ember s` or `forego` in rails

but those processes have cleanup routines that run after `pndev` has already exited because they appear to happen in separate processes that are forked.

Unless we're willing to do a TON of work on signal handling this will be hard to fix

I propose that you just press ENTER once you CTRL+C a `pndev start` and be ok w/it for now :)
