### ISSUE TITLE
Restructure command.rs into separate files

### ISSUE THREAD

**Issue by typeoneerror** [PrecisionNutrition/pndev#52]
It'd be great if there was a base Command and each cli  command was extracted to it's own file.

```
commands/
    base.rs
    run.rs
    start.rs
```

I can see commands.rs getting unwieldy going forwards.

**Comment by ghedamat** [comment]
Considering that I have small rust knowledge overall, here are my initial thoughts 

In my limited experience rust people are not afraid of very long files (1000s of lines).
We don't have any but AFAIK normally even tests are written within the source files.

So my take is that we are not yet in a place where a split is needed given also how much shared logic there is between commands.

My worry, and this is mostly my nature, is that the cost of abstraction would be more that it's worth right now.
That said I'd be happy to be persuaded otherwise! There might be an easy way to do this. I have not spent time yet thinking about how to implement this ask.
